---
title: "The Geometry of Archaeological Thought: Analysing discplinary change using word embeddings from conference abstracts"
output: bookdown::html_document2
bibliography: references.bib
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction

The study of disciplinary change traditionally relies on close reading of a large number of publications, manually sorting them into pre-defined categories and making connections between these groups and external influences [e.g. @trigger1989history]. These methods are time-consuming and expensive (because they depend on full access to a large library of texts), which limits participation in this aspect of archaeology. Computational approaches to analyzing text that can process many publications quickly to generate topics in a bottom-up fashion offer a new way to investigate disciplinary history. This has the advantage of increasing and diversifying participation in study of the history of archaeology, as well as  more comprehensive, systematic, and reproducible analyses of the contents of large number of full-text documents. The methods and data we present here offer empirical basis for what might otherwise be informal claims about the discipline and its history. They are also the type of data that may prompt discussion about the directions the discipline might — or could — take.

In this paper we present a dataset of all available abstracts of papers and posters presented at annual meetings of the Society of American Archaeology. We demonstrate the use of word embeddings, a commonly used computational tool in natural language processing (NLP) and machine learning, as a method to measure, quantify, and compare changes in the way archaeologists write cf. [@Garg2018; @Kozlowski2019]. We present the temporal reference plot as a method for visualizing disciplinary change in archaeology. As a case study, we use these data and methods to explore how archaeologists' writing about explaining and theorizing the past have changed over time.

# Background

Research into the history of archaeology is often organised into two major phases. An early internalist phase, where the story of development of the field is told with limited reference to the influence of political, social, religious, and economic institutions. In the 1980s an external, critical history phase began, seeking to understand the interactions between archaeological practice and its political, economic and social contexts.

Among historians of archaeology there are two major phases in  ‘critical history of archaeology’ in the 1980s had been characterized by the replacement of an 

- previous efforts at the history of archaeology (e.g. Bruce Trigger's book)
- previous efforts at text analysis in archaeology (e.g. bibliometrics, citation networks)

# Methods

- source of the data

The data for our study comes from the text of oral and poster presentation abstracts presented at the annual meetings of the Society of American Archaeology (SAA). The earliest meeting in our data is 19XX, and we have some years missing, especially XXXX-XXXX. The total number of abstracts is 68,176 (xxx words) from 40 annual meetings. We obtained PDF files of annual programs from https://www.saa.org/annual-meeting/annual-meeting-archives/program-archives. 

The PDFs for the years XXXX-XXXX contain images of pages, and after 2005 the PDFs are searchable text. We converted the page images from PDF to PNG files using ImageMagick software, and then used optical character recognition to extract text from the PNG files with the Tesseract package [@Kay2007]. We obtained an acceptable rate of 95-98% word-level OCR accuracy across the PDFs [citation]. After OCR, we used the quanteda package  [@Benoit2018] to remove punctuation, numbers, and stopwords, such as "the", "an", "a", [specifically why do we remove stopwords?]. 

- something about basic steps
-- transform text into dfm, define dfm... 

- word embeddings (cite our readings)
-- a few sentences to introduce the reader to how WE have been used in other recent studies. this is a little bit background. '...recently used in many social science fields to...' tell the reader what was the finding of some key studies using WE that have inspired us. 

<!-- There are two major word-level pretrained word embeddings, Word2Vec and Glove according to different methods used for training [@Rong2014; @Pennington2014]. --> 

-- then some more detail about the mechanics of the method, as we are using it. Say how what we did works in general. 

In this article, we trained word embeddings with the GloVe model using th text2vec package [@Selivanov2016]. The GloVe model calculates ... creates the co-occurrence matrix. 

- temporal referencing plots (cite our readings)

# Results

- basic details (e.g. word and abstract counts)
- word frequency time series
- TR plots

# Discussion

- ...

# Conclusion

- ...

# Acknowledgements

# References 

<!--- use the bib file --> 



